### ISSUE TITLE
Unable to Filter Entities

### ISSUE THREAD

**Issue by Reigningfear** [rappen/BulkDataUpdater#155]
Hello,

first and foremost, thank you for your effort with this tool, it has been very helpful for me. I recently ran into an issue where I was trying to filter a custom entity and continually received this error log:
"
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at XrmToolBox.Extensibility.Worker.CancelWorker()
   at Cinteros.XTB.BulkDataUpdater.BulkDataUpdater.RetrieveRecords(String fetch, Action AfterRetrieve)
   at Cinteros.XTB.BulkDataUpdater.BulkDataUpdater.FetchUpdated(String fetch)
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at XrmToolBox.New.PluginForm.SendIncomingBrokerMessage(MessageBusEventArgs message)
   at XrmToolBox.New.NewForm.MainForm_MessageBroker(Object sender, MessageBusEventArgs message)
   at Cinteros.Xrm.FetchXmlBuilder.FetchXmlBuilder.ReturnToCaller()
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
"
This appears to be new as I have done this sort of filtering countless times before. I did recently update the xrmtoolbox app and I believe this is the first time i've used your tools after the update. 

My steps are:

1. select entity
2. all-attributes
3. filter on 1 or more fields.
4. execute - this works and shows results.
5. 'Return FetchXML' to FetchXML Updater
6. Immediate Error.

Please let me know if there is anything else I can provide. 

---
- Deployment: Online
- DB Version: 9.2.22013.141
- Connection Controls Version: 1.2021.9.46
- XrmToolBox Version: 1.2021.12.53
- Tool Version: 1.2022.2.1

**Comment by Reigningfear** [comment]
It does not. I attempted to select a single attribute and send the results to Bulk Data Uploader. The error message appears to be different:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.MissingMethodException: Method not found: 'Void XrmToolBox.Extensibility.PluginControlBase.ShowErrorDialog(System.Exception, System.String, System.String, Boolean)'.
   at Cinteros.XTB.BulkDataUpdater.BulkDataUpdater.<>c__DisplayClass10_0.<RetrieveRecords>b__1(RunWorkerCompletedEventArgs completedargs)
   at XrmToolBox.Extensibility.Worker.<>c__DisplayClass4_0.<WorkAsync>b__0(Object s, RunWorkerCompletedEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)
   
   
  May or may not be helpful but If I open 'Edit FetchXML' and click ok to effectively reload the query, I get the first error message I posted. I have tried complex columns attributes and simple column attributes with the same result.

**Comment by rappen** [comment]
Thanks,
If you update then XrmToolBox to latest (1.2022.2.54), you will (probably...) get better error message.

Can I see the fetchxml you are using when it fails?

**Comment by rappen** [comment]
Ping @Reigningfear - any more info, or this issue should be closed?
I would like to fix it if there is a bug in the tool...

**Comment by rappen** [comment]
Closing now - please reopen if more issues appear.
