### ISSUE TITLE
Entity Id must be specified for Update

### ISSUE THREAD

**Issue by scottgolightly** [rappen/BulkDataUpdater#174]
During an update of a boolean field earlier today I got an error from a plugin. After that error the same update statement gives me this error. I have tested the update against production (where I was updating earlier today) and our test environment with the same results.
I have also tried uninstalling and reinstalling Bulk Data Updater. I have tried rebooting my system but to no avail. 

![image](https://user-images.githubusercontent.com/4343718/191864556-6f5cf8b4-9f3e-4a55-ad16-8ff64913a002.png)

![image](https://user-images.githubusercontent.com/4343718/191864474-b88363dc-8f1c-44f5-85a3-a37cc07c9a64.png)
Error Time: 2022-09-22 16:43:23.576
System.ServiceModel.FaultException<Microsoft.Xrm.Sdk.OrganizationServiceFault> (0x80040203)
Entity Id must be specified for Update
mscorlib
Server stack trace: 
   at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at Cinteros.XTB.BulkDataUpdater.BulkDataUpdater.<>c__DisplayClass49_0.<UpdateRecords>b__1(BackgroundWorker bgworker, DoWorkEventArgs workargs)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
---
- Deployment: Online
- DB Version: 9.2.22083.172
- Connection Controls Version: 1.2022.7.53
- XrmToolBox Version: 1.2022.5.56
- Tool Version: 1.2022.8.1

**Comment by rappen** [comment]
That's bad...
Can you send the query (FetchXML) that you use?

Just curious - you update 15000 records, one by one, and waiting 2 minutes between each...? That would take more that 20 days...

**Comment by MscrmTools** [comment]
Additional info : This error occurs if the primary key is not specified in the fetchxml.

More over, the issue occurs only if batch is set to 1. If more than one, no error is detected (but the update does not occur at all) but lors report success for all lines.

**Comment by MscrmTools** [comment]
@rappen this one seems relatively easy to fix (if not done yet): Maybe automatically add primary key attribute in fetchxml if it's not already there

**Comment by rappen** [comment]
The issue seems to be `distinct='true'` and id attribute is not included.
This is now controlled when retrieving records.
Note: Without distinct, the id's are always included even without the added attributed.
