### ISSUE TITLE
UI error

### ISSUE THREAD

**Issue by rappen** [rappen/BulkDataUpdater#217]
Stack:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Rappen.XTB.Helpers.ControlItems.AttributeMetadataItem.ToString()
   at Cinteros.XTB.BulkDataUpdater.BulkDataUpdater.AddBAI(BulkActionItem bai)
   at Cinteros.XTB.BulkDataUpdater.BulkDataUpdater.<SetUpdateFromJob>b__70_0(BulkActionItem a)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Cinteros.XTB.BulkDataUpdater.BulkDataUpdater.SetUpdateFromJob
```

**Comment by LukePa1mer** [comment]
This error has started for me this morning when opening BDU.  Any work around?

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Rappen.XTB.Helpers.ControlItems.AttributeMetadataItem.ToString()
   at Cinteros.XTB.BulkDataUpdater.BulkDataUpdater.AddBAI(BulkActionItem bai)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Cinteros.XTB.BulkDataUpdater.BulkDataUpdater.SetUpdateFromJob(JobUpdate job)
   at Cinteros.XTB.BulkDataUpdater.BulkDataUpdater.InitializeTab()
   at Cinteros.XTB.BulkDataUpdater.BulkDataUpdater.RetrieveRecordsReady()
   at XrmToolBox.Extensibility.Worker.<>c__DisplayClass4_0.<WorkAsync>b__0(Object s, RunWorkerCompletedEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)
