### ISSUE TITLE
AADSTS50196: The server terminated an operation because it encountered a client request loop.

### ISSUE THREAD

**Issue by tonyuccello** [rappen/BulkDataUpdater#245]
Keep getting this error when trying to retrieve records.

[Write any error info to resolve easier]

---
```
Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException:
AADSTS50196: The server terminated an operation because it encountered a client request loop. Please contact your app vendor. Trace ID: c847e3c8-1151-4a6d-b27e-dbe654f53300 Correlation ID: 35d2ea2d-e66a-4542-93c9-82da5c0bed73 Timestamp: 2024-10-31 00:43:01Z
Microsoft.IdentityModel.Clients.ActiveDirectory
- Microsoft.Identity.Core.OAuth2.OAuthClient.<GetResponseAsync>d__18`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
- System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
- System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
- Microsoft.Identity.Core.OAuth2.OAuthClient.<GetResponseAsync>d__17`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
- System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
- System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
- Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<SendHttpMessageAsync>d__75.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
- System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
- System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
- Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<SendTokenRequestAsync>d__72.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
- System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
- System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
- Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<CheckAndAcquireTokenUsingBrokerAsync>d__62.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
- System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
- System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
- Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<RunAsync>d__60.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
- System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
- System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
- Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenCommonAsync>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
- System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
- System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
- Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenAsync>d__33.MoveNext()
```

---
- XrmToolBox Version: 1.2024.9.69
- BulkDataUpdater Version: 1.2024.10.1
- DB Version: 9.2.24094.228
- Deployment: Online

**Comment by rappen** [comment]
That's un-nice... 😕

Do you have a gazillion records?
Do you get the same error when trying in FXB?

**Comment by tonyuccello** [comment]
Hey Rappen, yes, over 800K records. I ran a Bulk Delete Job overnight and reduced it by 430K and this morning was able to select 138K records and while using this Bulk Data Updater plug-in during the process it only asked me for login once.

It's currently showing it's going to take 5+ Hours! Yikes!

BTW, (pardon the ignorance), what is FXB ?

Cheers,
Tony

**Comment by RegularGMan** [comment]
I have the same issue.

In my case, I get the error when attempting to apply the update to the attribute. It repeatedly opens the Microsoft Login window, which then repeatedly closes instantly - after five popups, the window remains open and says "We couldn't sign you in. Please try again." 
After signing in (which sometimes doesn't even accept the 2-factor code), Bulk Data Updater resumes attempting to update for several seconds, then displays either the error posted by tonyuccello or "An error occurred while sending the request" (Source: mscorlib)

**Additional Error Log for "An error occurred while sending the request"**
```
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Core.Http.HttpManager.<ExecuteAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Core.Http.HttpManager.<ExecuteWithRetryAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Core.Http.HttpManager.<SendPostAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Core.Http.HttpManager.<SendPostAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Core.OAuth2.OAuthClient.<ExecuteRequestAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Core.OAuth2.OAuthClient.<GetResponseAsync>d__18`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Core.OAuth2.OAuthClient.<GetResponseAsync>d__17`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<SendHttpMessageAsync>d__75.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<SendTokenRequestAsync>d__72.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<CheckAndAcquireTokenUsingBrokerAsync>d__62.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<RunAsync>d__60.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenCommonAsync>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenAsync>d__33.MoveNext()
```

**Here's the FetchXML:**
```
<fetch top="500" distinct="true">
  <entity name="account">
    <attribute name="accountid" />
    <attribute name="btek_businesstype" />
    <filter>
      <condition attribute="btek_businesstype" operator="null" value="" />
      <condition entityname="opportunity" attribute="originatingleadid" operator="not-null" value="" />
      <condition entityname="originatinglead" attribute="btek_businesstype" operator="not-null" value="" />
    </filter>
    <link-entity name="opportunity" from="customerid" to="accountid" link-type="matchfirstrowusingcrossapply" alias="opportunity">
      <attribute name="opportunityid" />
      <attribute name="originatingleadid" />
      <attribute name="parentaccountid" />
      <link-entity name="lead" from="leadid" to="originatingleadid" link-type="inner" alias="originatinglead">
        <attribute name="btek_businesstype" />
        <attribute name="leadid" />
      </link-entity>
    </link-entity>
  </entity>
</fetch>
```

**Here's the XRM Token:**
`<expand|opportunity|parentaccountid|{originatingleadid.btek_businesstype.btek_businesstypeid}||, ||false>`
